# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDg1Njk2MmVhZjFjYzAyYTEzOTZlYTg3ZTAwNzczYmM1YTYyZDliNTdjZWM5YmJmOWRmZjRhZjU1YjEzMGQxODRhNWRhZjM4ZjNjNzI1ZjA2M2EwMGExOTIyY2U2YmYxN2M2Yzc0OTgzN2JlMjdmMmUwMTM4MjdjN2VkYzU5YTI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
